import os,sys
import time

##### Progressbar1 #####
def prog1():
 #colors:
 G='\033[0;30;42m'
 W='\033[37;40m'

 print(G+"Progress: [0%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [1%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [2%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [3%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [4%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [5%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [6%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [7%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [8%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [9%]"+W+" [..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [10%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [11%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [12%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [13%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [14%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [15%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [16%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [17%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [18%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [19%]"+W+" [#.........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [20%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [21%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [22%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [23%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [24%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [25%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [26%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [27%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [28%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [29%]"+W+" [##........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [30%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [31%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [32%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [33%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [34%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [35%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [36%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [37%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [38%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [39%]"+W+" [###.......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [40%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [41%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [42%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [43%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [44%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [45%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [46%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [47%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [48%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [49%]"+W+" [####......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [50%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [51%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [52%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [53%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [54%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [55%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [56%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [57%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [58%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [59%]"+W+" [#####.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [60%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [61%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [62%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [63%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [64%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [65%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [66%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [67%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [68%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [69%]"+W+" [######....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [70%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [71%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [72%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [73%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [74%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [75%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [76%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [77%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [78%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [79%]"+W+" [#######...]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [80%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [81%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [82%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [83%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [84%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [85%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [86%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [87%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [88%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [89%]"+W+" [########..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [90%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [91%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [92%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [93%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [94%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [95%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [96%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [97%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [98%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [99%]"+W+" [#########.]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [100%]"+W+" [##########]")


##### Progressbar2 #####
def prog2():
 #colors:
 G='\033[0;30;42m'
 W='\033[37;40m'

 print(G+"Progress: [0%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [1%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [2%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [3%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [4%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [5%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [6%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [7%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [8%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [9%]"+W+" [....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [10%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [11%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [12%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [13%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [14%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [15%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [16%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [17%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [18%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [19%]"+W+" [##..................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [20%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [21%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [22%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [23%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [24%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [25%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [26%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [27%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [28%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [29%]"+W+" [####................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [30%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [31%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [32%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [33%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [34%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [35%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [36%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [37%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [38%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [39%]"+W+" [######..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [40%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [41%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [42%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [43%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [44%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [45%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [46%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [47%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [48%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [49%]"+W+" [########............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [50%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [51%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [52%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [53%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [54%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [55%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [56%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [57%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [58%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [59%]"+W+" [##########..........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [60%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [61%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [62%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [63%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [64%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [65%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [66%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [67%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [68%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [69%]"+W+" [############........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [70%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [71%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [72%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [73%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [74%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [75%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [76%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [77%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [78%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [79%]"+W+" [##############......]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [80%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [81%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [82%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [83%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [84%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [85%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [86%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [87%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [88%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [89%]"+W+" [################....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [90%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [91%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [92%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [93%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [94%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [95%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [96%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [97%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [98%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [99%]"+W+" [##################..]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [100%]"+W+" [###################]")


##### Progressbar3 #####
def prog3():
 #colors:
 G='\033[0;30;42m'
 W='\033[37;40m'

 print(G+"Progress: [0%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [1%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [2%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [3%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [4%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [5%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [6%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [7%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [8%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [9%]"+W+" [............................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [10%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [11%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [12%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [13%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [14%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [15%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [16%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [17%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [18%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [19%]"+W+" [###.........................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [20%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [21%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [22%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [23%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [24%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [25%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [26%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [27%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [28%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [29%]"+W+" [#####.......................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [30%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [31%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [32%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [33%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [34%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [35%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [36%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [37%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [38%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [39%]"+W+" [########....................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [40%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [41%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [42%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [43%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [44%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [45%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [46%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [47%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [48%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [49%]"+W+" [###########.................]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [50%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [51%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [52%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [53%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [54%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [55%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [56%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [57%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [58%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [59%]"+W+" [##############..............]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [60%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [61%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [62%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [63%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [64%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [65%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [66%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [67%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [68%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [69%]"+W+" [#################...........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [70%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [71%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [72%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [73%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [74%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [75%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [76%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [77%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [78%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [79%]"+W+" [####################........]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [80%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [81%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [82%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [83%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [84%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [85%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [86%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [87%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [88%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [89%]"+W+" [#######################.....]", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [90%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [91%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [92%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [93%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [94%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [95%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [96%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [97%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [98%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [99%]"+W+" [##########################..] ", end="\r")
 time.sleep(0.05)
 print(G+"Progress: [100%]"+W+" [############################]")
